name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      
      - name: Download Script
        run: |
          curl https://raw.githubusercontent.com/brainded-boi/temporary/test/build_rom.sh -o build_rom.sh
          
      - uses: rokibhasansagar/slimhub_actions@main
          
      - name: Start Build 
        run: |
          bash build_rom.sh         
